version: '3'
services:
  springboot-app:
    build: .
    container_name: spring-app
    image: cliente-backend
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - springmysql-net
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./services/db:/var/lib/mysql
    networks:
      - springmysql-net
    ports:
      - 3307:3306
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
networks:
  springmysql-net:
